import 'package:bachat_cards/theme/theme.dart';
import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';

class TermsConditionsScreen extends StatelessWidget {
  const TermsConditionsScreen({super.key, this.terms});
  final String? terms;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.black),
        title: Text(
          'Terms And Conditions',
          style: poppinsSemiBold24.copyWith(color: Colors.black),
        ),
      ),
      body: SingleChildScrollView(
          child: Padding(
        padding: const EdgeInsets.all(20),
        child: terms != null
            ? Html(
                data: terms ?? '',
              )
            : Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                const Text(
                    'EARNEST DATA ANALYTICS Private Limited (“Bachat Card” "we" or “us” or “our”) owns and operates the website, bachatcard.in, the mobile and touch versions and any sites we have now or in the future that reference these Terms of Use (collectively, "Site"). By using the Site and Bachat card’s services through the Site, you agree to these Terms of Use (defined below) and any additional terms applicable to certain programs in which you may elect to participate. You also agree to our Privacy Statement, located at http:// bachatcard.in/privacy, and acknowledge that you will regularly visit the Terms of Use (defined below) to familiarize yourself with any updates. The Privacy Statement, together with these terms of use, and any other terms contained herein or incorporated herein by reference, are collectively referred to as the "Terms of Use." The term "using" also includes any person or entity that accesses or uses the Site with crawlers, robots, data mining or extraction tools or any other functionality. If you have any questions about our terms, feel free to contact us at support@ bachatcard.in.'),
                const Text(
                    '\nThis document is an electronic record in terms of the IT Act and generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 of the IG Rules that provide for the due diligence to be exercised by the Website.'),
                const Text(
                    '\nIF YOU DO NOT AGREE TO THESE TERMS OF USE, IMMEDIATELY STOP USING THE SITE AND DO NOT USE ANY WORK ADVANTAGE SERVICE, PARTICIPATE IN ANY PROGRAM OR PURCHASE ANY VOUCHER, PRODUCT OR OTHER GOOD OR SERVICE OFFERED THROUGH THE SITE.'),
                const Text(
                  '\nTERMS AND CONDITIONS FOR PRE-PAID INSTRUMENTS',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nThese Terms (as defined hereinafter) shall be read in conjunction with the Terms and shall be applicable to the Bachat Card PPI issued by EARNEST DATA ANALYTICS Private Limited unless the Terms conflict with the Bachat Card PPI Terms stated herein below in which case the Terms shall prevail:'),
                const Text(
                    '\nNo Transactions Without KYC\nThere shall be no Transactions without compliance with KYC requirements. the User understands and agrees that Bachat card reserves the right to take all steps necessary to ensure compliance with all applicable KYC and legal requirements. Bachat card may require the User to submit all requisite KYC related information at the time of the User\'s access to the Services.'),
                const Text(
                    '\nBachat Card Right to Discontinue\nThe User acknowledges that EARNEST DATA ANALYTICS Private Limited has the right to discontinue the Services or reject applications for Bachat Card PPI at any time:'),
                const Text(
                    '\nIf the information and supporting documents provided by the User bear discrepancies; or'),
                const Text(
                    '\nFor any suspected violation of the rules, regulations, orders, directions, notifications issued by RBI from time to time or for any violation of these Terms or any law for the time being in force; or'),
                const Text(
                    '\nTo combat potential fraud, sabotage, willful destruction, threat to national security or for any other force majeure event.\n\nIf Bachat Card believes, in its reasonable opinion, that cessation/suspension is necessary for any other legitimate purpose.'),
                const Text(
                    '\nRisk restricted Merchant Categories\nBelow mentioned are the risk restricted merchant categories on which Pine Labs PPIs cannot be used and the list can be revised from time to time:'),
                const SizedBox(
                  height: 8,
                ),
                _table(),
                const Text(
                  '\nBACHAT E-CARD TERMS AND CONDITIONS',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nThe following terms and conditions are applicable to the Purchaser upon purchase of the Bachat e-Card through EARNEST DATA ANALYTICS Private Limited:'),
                const Text(
                    '\nAll Bachat e-Card shall be valid for 3 years from date of issue and shall remain valid till the date mentioned on the face of the Bachat e-Card. The validity of Bachat e-Card may be extended, or a replacement card may be issued on expiry, upon request from the Purchaser or the Cardholder subject to applicable fees and at the sole discretion of EARNEST DATA ANALYTICS Private Limited.'),
                const Text(
                    '\nThe Bachat e-Cards can be redeemed at any of the websites which accept RuPay instruments as and by way of payment. However, there are a few merchant categories, as mentioned below, wherein the Bachat e-Cards cannot be redeemed.'),
                const SizedBox(
                  height: 8,
                ),
                _table(),
                const Text(
                    '\nUnder no circumstances whatsoever, is the return or cancellation of Bachat e-Cards permitted once the same have been generated and delivered to the Purchaser.'),
                const Text(
                    '\nThe Bachat e-Cards cannot be reloaded, resold, transferred for value or redeemed/exchanged for its value in cash by the Cardholder. Cash withdrawal facility is not available on Bachat e-Card.'),
                const Text(
                    '\nIf the Cardholder information provided by the Purchaser or the Cardholder is found to be incorrect, the Bachat e-Card in question is liable to be cancelled and the entire amount forfeited, and no claims in respect thereof will be entertained by EARNEST DATA ANALYTICS Private Limited.'),
                const Text(
                    '\nThe Purchaser shall indemnify, defend and hold harmless EARNEST DATA ANALYTICS Private Limited from and against any and all third-party liability, losses, costs and expenses (including reasonable attorneys’ fees) relating to or arising out of the breach of these terms and conditions, the negligence or willful misconduct or fraud by the Purchaser, or its employees or agents.'),
                const Text(
                    '\nEARNEST DATA ANALYTICS PVT. LTD. DOES NOT MAKE ANY WARRANTIES, EXPRESS OR IMPLIED, WITH RESPECT TO THE BACHAT E-CARDS, INCLUDING WITHOUT LIMITATION, ANY EXPRESS OR IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. IN THE EVENT A GIFT CARD IS NON-FUNCTIONAL, THE PURCHASER AND THE CARDHOLDER’S SOLE REMEDY WILL BE THE REPLACEMENT OF SUCH GIFT CARD.'),
                const Text(
                    '\nAll fees, surcharges, goods and applicable taxes with respect to Bachat e-Card shall be borne by the Purchaser or the Cardholder. EARNEST DATA ANALYTICS Private Limited shall have no liability towards the same. There may be surcharge applicable on certain card transactions. In such an event, the same will be deducted from the card balance available in the Bachat e-Card at the time of transaction. In case the card balance is not enough to provide for the surcharge the transaction shall be declined.'),
                const Text(
                    '\nNo request for change in mobile number linked to a card will be entertained once the card has been issued and activated. Any change of Cardholder credentials like e-mail if provided will have to be communicated by the Purchaser only. The Card Holder cannot request for any changes directly. Cardholders can check the available balance of cards by logging in on the Bachat Card Website (www.bachatcard.in) and Bachat Card Mobile App.'),
                const Text(
                    '\nEARNEST DATA ANALYTICS Private Limited may, from time-to-time issue certain special categories of e-gift cards, which can be accepted only at specific merchant categories. Such special category e-gift cards shall be governed by the terms and conditions set out here.'),
                const Text(
                    '\nAny dispute in relation to the Bachat e-Cards shall be referred to EARNEST DATA ANALYTICS Private Limited. and the decision of Bachat Cards shall be final in this regard. Any disputes and claims in relation to the Bachat Cards shall be subject to the laws of India and the jurisdiction of the courts at New Delhi.'),
                const Text(
                    '\nThe Cardholder shall inform EARNEST DATA ANALYTICS Private Limited, by contacting the Customer Care at 8700181782 or email at support@bachatcard.in, within 15 (Fifteen) days of occurrence of any transaction, if any irregularities or discrepancies exist in such transaction or if such Cardholder has any query or complaint in relation to the Transaction. If EARNEST DATA ANALYTICS Private Limited does not receive any information to the contrary within 15 (Fifteen) days of occurrence of any Transaction, it shall be entitled to assume and proceed on the basis that the relevant Transaction(s) was affected without any irregularity/ discrepancy. Subject to the foregoing, all transactions as aforesaid shall be dealt with in accordance with the Customer Grievance Redressal Policy of EARNEST DATA ANALYTICS Private Limited which can be accessed at this link: www.bachatcard.in/complain'),
                const Text(
                    '\nRevalidation & Replacement of Bachat Cards: For renewal of your previous non-Network PPI\'s issued by EARNEST DATA ANALYTICS Private Limited, users can write to support@bachatcard.in for replacement of card with Bachat card.'),
                const Text(
                  '\n\nYOUR AGREEMENT WITH BACHAT CARD',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nWe reserve the right to modify the Terms at any time without giving you any prior notice. Your use of the Website following any such modification constitutes your agreement to follow and be bound by the Terms as modified. Any additional terms and conditions, disclaimers, privacy policies and other policies applicable in general and/ or to specific areas of this Website or to particular Service are also considered as Terms.'),
                const Text(
                    '\nYou acknowledge that you will be bound by this Agreement for availing any of the Services offered by us.'),
                const Text(
                    '\nYour access to use of the Website and the Services will be solely at the discretion of Bachat Card.'),
                const Text(
                    '\nIf you do not agree to be bound by (or cannot comply with) any of the terms below, please leave the Website immediately and terminate your account with us. The information that you obtain or receive from Bachat Card, its Team, contractors, partners, sponsors, advertisers or otherwise on the Website is for informational and scheduling purposes only.'),
                const Text(
                    '\nThe information provided on the Website is not professional advice and must not be considered as such. Your use of information provided on the Website is solely at your own risk.'),
                const Text(
                    '\nYou can accept the Terms by:\n\nUsing the Website; or\n\nBy actually using the Services. In this case, you understand and agree that Bachat Card will treat your use of the Services as acceptance of the Terms from that point onwards.'),
                const Text(
                    '\nFor being a valid User, you must satisfy the following conditions:'),
                const Text(
                    '\nYou are of legal age to form a binding contract with Bachat Card; or'),
                const Text(
                    '\nYou are not a person barred from receiving the Services under the laws of India or other countries including the country in which you are resident or from which you use the services.'),
                const Text(
                    '\nI give consent to Bachat Card to collect KYC documents from PSUs and Government agencies on my behalf.'),
                const Text(
                  '\nINFORMATION PRESENTATION/ EDITORIAL CONTROL',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nWe make the Website available as a part of our Service to Holders and Merchants. We may, but have no obligation to, have non-user-posted information reviewed by the Website\'s editorial personnel.'),
                const Text(
                    '\nIt is important to note, however, that the timeliness and accuracy of any or all of the information is not guaranteed. Neither the authors, the editorial personnel, nor any other party who has been involved in the preparation or publication of this work can assure you that the information contained herein is in every respect accurate or complete, and they are not responsible for any errors or omissions or for the results obtained from the use of such information.'),
                const Text(
                  '\nUSE OF SERVICES AND INFORMATION ON THE WEBSITE',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                  '\nIn order to access certain Services, you may be required to provide information about yourself (such as identification, contact or payment details) as part of the registration process for the Service, or as part of your continued use of the Services. You agree that any registration information you give to us will always be true, accurate, correct, complete and up to date. Any phone number used to register with the Website needs to be registered in your name and you might be asked to provide supporting documents to prove the same.',
                ),
                const Text(
                    '\nInformation provided by Bachat Card or otherwise obtained from the Website will not be used for any unauthorized and unlawful purpose.'),
                const Text(
                    '\nYou agree not to access (or attempt to access) any of the Services by any means other than through the interface that is provided by Bachat Card, unless you have been specifically allowed to do so in a separate agreement with us;'),
                const Text(
                    '\nYou agree that you will not engage in any activity that interferes with or disrupts the Services (or the servers and networks which are connected to the Services);'),
                const Text(
                    '\nYou agree that you will not reproduce, duplicate, copy, transfer, license, rent, sell, trade or resell the information obtained from the Website for any purpose whatsoever.'),
                const Text(
                    '\nYou agree that you are solely responsible for (and that Bachat Card has no responsibility to you or to any third party for) any breach of your obligations under the Terms and for the consequences (including any loss or damage which Bachat Card may suffer) of any such breach.'),
                const Text(
                    '\nYou will not impersonate another person, including, without limitation, a Holder or a Merchant.'),
                const Text(
                    '\nYou agree to the use of your data in accordance with Bachat Card\'s Privacy Policy.'),
                const Text(
                    '\nAll personal and contact information provided by you will be kept confidential by Bachat Card. This includes your personal information given in relation to your account creation and subsequent administration.'),
                const Text(
                  '\nYOUR SUBMITTED INFORMATION',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nOn creation of an account on the Website, you will have the opportunity to use various interactive aspects through which you can communicate with our Team and share information (collectively "Submitted Information"). It is important that you act responsibly when providing such Submitted Information. Do not use inappropriate language, make gratuitous personal criticisms or comments. When participating in interactive aspects of the Service, please do include all relevant information in a concise manner to help us provide you with a helpful response.'),
                const Text('\nPlease note that:'),
                const Text(
                    '\nYou are solely responsible for any Submitted Information that you submit on the Website or transmit to our Team and/or other users of the Website;'),
                const Text(
                    '\nYou may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights. You may not submit any content or material that infringes, misappropriates or violates the intellectual property, publicity, privacy or other rights of any party;'),
                const Text(
                    '\nYou may not provide any Submitted Information that falsely expresses or implies that such content or material is sponsored or endorsed by Bachat Card;'),
                const Text(
                    '\nYou may not provide any Submitted Information that is unlawful or that promotes or encourages illegal activity;'),
                const Text(
                    '\nYou understand and agree that Bachat Card may (but is not obligated to) review and delete any Submitted Information that in the sole judgment of Bachat Card violates these Terms or which might be offensive, illegal, or that might violate the rights of, harm, or threaten the safety of other users of the Website and/or any other person;'),
                const Text(
                    '\nYou agree that you will only provide Submitted Information that you believe to be true and you will not purposely provide false or misleading information; and'),
                const Text(
                    '\nThe following is a partial list of the kind of content and communications that are illegal or prohibited on/through the Website. Bachat Card reserves the right to investigate and take appropriate legal action in its sole discretion against anyone who violates this provision, including without limitation, removing the offending communication from the Services and terminating the membership of such violators or blocking your use of the Services and/or the Website. You may not post content that:'),
                const Text(
                    '\nInvolves the transmission of unsolicited mass mailing or "spamming"'),
                const Text(
                    '\nHarasses or advocates harassment of another person'),
                const Text('\nIs false or intentionally misleading'),
                const Text(
                    '\nViolates the intellectual property or other rights of any person'),
                const Text(
                    '\nIs threatening, obscene, defamatory or libelous. or'),
                const Text('\nIs pornographic or sexually explicit in nature.'),
                const Text(
                    '\nYou agree, through Your use of this Service, that you will not use this Website to post any material which known to be unlawful, false and/or defamatory, inaccurate, abusive, vulgar, hateful, harassing, libelous, harmful, obscene, profane, sexually oriented, threatening, racially offensive, invasive of a person\'s privacy, or otherwise objectionable material of any kind or nature. You agree not to post any copyrighted material unless the copyright is owned by You or You have been given permission by the copyright owner to post such material and You give due credit to the copyright owner by including the copyright information in your post.'),
                const Text(
                    '\nYou agree and acknowledge that you will not submit unlawful, offensive, inaccurate, misleading, abusive, pornographic, harassing, libelous, blasphemous, defamatory, obscene, pedophilic, invasive of another\'s privacy, hateful, racially or ethically objectionable, disparaging, relating to or encouraging money laundering or gambling, or otherwise inappropriate material.'),
                const Text('\nYou also agree that you will:'),
                const Text(
                    '\nNot upload or share any information that impersonates another person, threatens the unity, integrity, defense, security or sovereignty of India;'),
                const Text(
                    '\nObtain any consents, permission or licenses that may be legally required for you to submit any material;'),
                const Text('\nRespect the privacy of others;'),
                const Text(
                    '\nNot distribute or post spam, unreasonably large files, chain letters, pyramid schemes, viruses;'),
                const Text(
                    '\nNot use any other technologies or initiate other activities that may harm the Service, or the interest or property of the Users; and'),
                const Text(
                    '\nNot use any automated systems or means to access, acquire, copy or monitor any part of the Service.'),
                const Text(
                    '\nYou will notify Bachat Card at Bachat Card Helpdesk upon coming across any objectionable content on the Website and Bachat Card shall use best efforts to remove such objectionable content within thirty-six hours from being duly notified.'),
                const Text(
                  '\nYOUR USE OF INFORMATION',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nExcept for Submitted Information that you submit, all of the information available on or through the Services and/or the Website, including without limitation, text, photographs, graphics and video and audio content, is owned by us and our licensors and is protected by copyright, trademark, patent and trade secret laws, other proprietary rights and international treaties. You acknowledge that the Services and any underlying technology or software used in connection with the Services contain Bachat Card\'s proprietary information. We give you permission to use the aforementioned content for personal, non-commercial purposes only and do not transfer any intellectual property rights to you by virtue of permitting your use of the Services. You may print, download, and store information from the Website for your own convenience, but you may not copy, distribute, republish (except as permitted in this paragraph), sell, or exploit any of the content, or exploit the Website in whole or in part, for any commercial gain or purpose whatsoever. Except as is expressly and unambiguously provided herein, we do not grant you any express or implied rights, and all rights in the Website and the Services not expressly granted by us to you are retained by Bachat Card.'),
                const Text(
                    '\nWe make no guarantees, representations or warranties, whether expressed or implied, with respect to professional qualifications, expertise and quality of work or services or other information concerning the Team.'),
                const Text(
                  '\nDISCLOSURE',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nBachat Cards may employ multiple mechanisms that rely on user\'s personal, transactional, financial, device, location and such other data gathered either directly, indirectly, through telemetry from its own applications or from any third-party applications or various other sources both related to or unrelated to Bachat Cards to detect, prevent, deter, mitigate and expose fraudulent behavior or any suspicious activity.'),
                const Text(
                    '\nBachat Cards may disclose, in strict confidence, to other institutions, such personal Information of the customer as may be reasonably necessary for reasons inclusive of:'),
                const Text(
                    '\nFor participation in any telecommunication or electronic clearing network'),
                const Text('\nIn compliance with a legal directive'),
                const Text('\nFor fraud prevention purposes'),
                const Text(
                  '\nPRIVACY AND INTELLECTUAL PROPERTY PROTECTION',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nBachat Card\'s Privacy Policy explains how we treat your personal data and protect your privacy when you use our Services. By using our services, you agree that Bachat Card can use such data in accordance with our policies.'),
                const Text(
                    '\nYou agree and understand that you are responsible for maintaining the confidentiality of passwords associated with any account you use to access the Services.'),
                const Text(
                    '\nYou agree that you will be solely responsible to Bachat Card for all activities that occur under your account.'),
                const Text(
                    '\nIf you become aware of any unauthorized use of your password or of your account, you agree to notify us immediately at Bachat Card Helpdesk.'),
                const Text(
                    '\nAll trademarks, brands and service marks used in conjunction with the Services offered by Bachat Card and owned by Bachat Card shall be our property; Bachat Card shall own all of the copyrights and database rights in the Services. Without our consent, you may not publish, distribute, extract or reproduce any contents provided by the Services. For use of any third party\'s intellectual property, you need to get permission directly from the owner of the intellectual property for any use. Third party trademarks may appear on this Website and all rights therein are reserved to the registered owners of those trademarks.'),
                const Text(
                    '\nAs a user of our Website, you acknowledge that any intellectual property which is not specifically mentioned to be owned by us is owned by their respective owners and the owners have a right to take appropriate actions against you for any violation, infringement and passing off.'),
                const Text(
                    '\nYour use of the Services is at all times governed by and subject to laws regarding copyright, trademark, patent, and trade secret ownership and use of intellectual property. You agree not to upload, download, display, perform, transmit, or otherwise distribute any information or content in violation of any party\'s copyrights, trademarks, patents, trade secrets, or other intellectual property or proprietary rights. You agree to abide by laws regarding copyright, trademark, patent, and trade secret ownership and use of intellectual property, and you shall be solely responsible for any violations of any laws and for any infringements of any intellectual property rights caused by use of the interface/Website.'),
                const Text(
                  '\nTHIRD PARTY INFORMATION ON THE APPLICATION',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nAs some information appearing on the Website is provided to Bachat Card by third parties, Bachat Card will have no liability in respect of any loss or damage arising from third party information which appears on the Website, including the manner in which the information is displayed or information which may be:'),
                const Text(
                    '\nOut of date;\nInaccurate;\nDuplication;\nImpersonation by a person to be another person.'),
                const Text(
                    '\nAll dealings and communication arising from Bachat Card\' facilitation of interaction between Merchant and Holder will be between the Merchant and Holder only and Bachat Card is not responsible in any manner for any communication between the Holder and the Merchant and has no liability in respect of such dealings whatsoever.'),
                const Text(
                    '\nBachat Card is not an agent for any of the Merchants listed on this Website and Bachat Card has no responsibility for and no liability whatsoever in respect of the conduct of a Merchant or quality of service provided by a Merchant.'),
                const Text(
                  '\nLINKS TO OTHER SITES',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nThe Services may include links to other websites. Some of these websites may contain materials that are objectionable, unlawful, or inaccurate. These links are provided for your convenience only and the provision of these links does not mean that we endorse these websites or the products and services they provide. You acknowledge and agree that we are not responsible or liable for the content or accuracy of these other websites.'),
                const Text(
                    '\nYou will note that the URL to every webpage on our Website begins with "https://". In other words, every webpage on our Website is hypertext transfer protocol secure ("HTTPS Enabled") or "identity verified".'),
                const Text(
                    '\nWe have had our entire Website HTTPS Enabled to better protect your security against dummy websites. Please verify that a webpage is HTTPS Enabled before providing any information on it. We will not be liable for any consequences of you providing details on any third-party website, including dummy websites.'),
                const Text(
                  '\nNO WARRANTIES',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nThe interface/Website is provided subject to all of the terms set forth in the Terms.'),
                const Text(
                    '\nWe make no guarantees, representations or warranties, whether expressed or implied, with respect to professional qualifications, expertise and quality of work or services or other information concerning the Team.'),
                const Text(
                    '\nBachat Card disclaims all warranties whether express or implied, including but not limited to:'),
                const Text(
                    '\nThat our Website will always function without disruptions, delay or errors. A number of factors may impact the quality of your communications and use of the Website and may result in the failure of your communications including but not limited to: your local network, firewall, your internet service provider, the public internet, the public switched mobile network, private switched mobile networks and your power supply. We take no responsibility for any disruption, interruption or delay caused by any failure of or inadequacy in any of these items or any other items over which we have no control;'),
                const Text(
                    '\nYour ability to use the Service through the Website;\nYour satisfaction with the Service or the Website;\nSecurity and privacy of your data;\nThat bugs or errors in the Service and/or Website will be corrected;'),
                const Text(
                    '\nThat our Services will be compatible with all broadband services and modems and we disclaim any express or implied warranties regarding the compatibility of our Service with any particular broadband service or modems;'),
                const Text(
                    '\nWe make no express or implied representations or warranties about our Services or the Website and disclaim any implied warranties, including, but not limited to, warranties or implied warranties of merchantability or fitness for a particular purpose or use or non-infringement. We do not authorize anyone to make a warranty on our behalf and you may not rely on any statement of warranty as a warranty by us; and'),
                const Text(
                    '\nThat our Team who furnishes Services to you in connection with this Agreement or the Service will be liable for any act or omission in relation to the Website.'),
                const Text(
                  '\nRESTRICTIONS ON USE',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nIn addition to all Terms of this Agreement, you shall not:'),
                const Text(
                    '\nUse the third party links to sites without agreeing to their website terms & conditions;'),
                const Text(
                    '\nPost links to third party websites or use their logo, company name, etc. without their prior written permission; or'),
                const Text(
                    '\nUse the Services for spamming and other illegal purposes.'),
                const Text(
                  '\nSPAMMING',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nYou may not use contact information provided by us or other users or harvest such information for the purpose of sending, or to facilitate the sending, of unsolicited bulk communications such as spam. You may not allow others to use your account to violate the terms of this section. We may terminate your membership or access to the Website immediately and take other legal action if you or anyone using your credentials violates these provisions.'),
                const Text(
                  '\nADDITIONAL TERMS',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nCertain Services on the Website may have additional terms (such as policies, guidelines, and rules) that will further govern your use of that particular Service and supplement these Terms. If you choose to register for or access any such Services, you will be presented with any relevant additional terms and conditions at that time. By using those Services, you agree to comply with such additional guidelines and rules.'),
                const Text(
                  '\nDISCLAIMER',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nThe Service and the Website and its entire contents are provided on an \'as is\' basis. Bachat Card and its officers, employees, agents and contractors give or make no representation or warranty (either express or implied) as to the suitability of the Service or the Website or its contents for any purpose or the completeness, accuracy, reliability, security or availability of the Service or the Website or its contents; nor do they accept any responsibility arising in any way (including from negligence) for errors in, or omissions from, the Service or the Website.'),
                const Text(
                    '\nBachat Card and its officers, employees, agents and contractors are not liable for any loss, damage, claim, expense, cost (including legal costs) or liability arising directly or indirectly from your use or non-use of the Service or the Website, or your reliance upon the Service or the information contained upon the Website (whether arising from Bachat Card\' or any other person\'s negligence or otherwise).'),
                const Text(
                    '\nYou and Bachat Card agree that any cause of action arising out of your use of the Service or Website must be commenced within 12 (twelve) months after the cause of action accrues or you become aware of the facts giving rise to the cause of action, whichever is later. Otherwise, such cause of action is permanently barred.'),
                const Text(
                    '\nWhere any legislation implies any term, condition, representation or warranty into this Agreement or the Privacy Policy and that legislation prohibits exclusion of that term, condition, representation or warranty, then that term, condition, representation or warranty is included.'),
                const Text(
                  '\nLIMITATION OF LIABILITY AND INDEMNIFICATION',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nYour sole and exclusive remedy for any dispute with us is the suspension of your Bachat Card account. In no event shall our total cumulative liability to you for any and all claims relating to or arising out of your use of the Website, regardless of the form of action, exceed INR 1000 /- (Indian Rupees One Thousand only).In no event shall we be liable to you (or to any third party claiming under or through you) for any indirect, special, incidental, consequential or exemplary damages arising from your use of, or inability to use, the Website. These exclusions apply to any claims for lost profits, lost data, loss of goodwill, work stoppage, computer failure or malfunction, any other commercial damages or losses, even if we knew or should have known of the possibility of such damages.'),
                const Text(
                    '\nYou agree to defend, indemnify and hold Bachat Card, and its Team harmless from and against any claims, actions, demands, liabilities, judgments, and settlements, including without limitation, reasonable legal fees resulting from or alleged to result from your use of this Website.'),
                const Text(
                    '\nYou hereby indemnify and hold Bachat Card, and its Team harmless from any loss, costs, damages, expenses, and liability caused by your use of the Website, your violation of this Agreement, or your violation of any rights of a third party through use of the Website.'),
                const Text(
                  '\nTERM AND TERMINATION',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nThis Agreement will remain in full force and effect while you use the Portal in any form or capacity.'),
                const Text(
                    '\nBachat Cards reserves the right to terminate your access to the Portal and this Agreement in the event of breach of any terms contained in this Agreement, misrepresentation of information, any unlawful activity or is unable to verify or authenticate any information the Users submit to Bachat Cards.'),
                const Text(
                    '\nClauses under the headings Limitation of Liability and Indemnification, Privacy and Intellectual Property Protection, Dispute Resolution, and Notices shall continue and survive the termination of this Agreement.'),
                const Text(
                    '\nYour account may be disabled and Services may be terminated based upon the representations made by you. Any of the following actions may result in termination of Services:'),
                const Text(
                    '\nImpersonating another person or entity with the effect of misleading users about the identity of the creator of content (including misleading account user names, voices and sounds used in broadcasts, and account profile information);'),
                const Text(
                    '\nImpersonating the Services or a Bachat Card Team member;'),
                const Text(
                    '\nRepresenting that content you post or transmit through the Services is created or endorsed by us;'),
                const Text(
                    '\nProviding or sending any content which may be harmful or detrimental to Bachat Card or its business associates, or which violates any restriction or policy established by Bachat Card or its business associates;'),
                const Text(
                    '\nSubmission of any content that falsely expresses or implies that such content is sponsored or endorsed by us;'),
                const Text(
                    '\nFalsification or deletion of any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is posted;'),
                const Text(
                    '\nPutting on Bachat Card\' system any content that contains software viruses, trojan horses or any other computer code, files, or programs designed to interrupt, destroy, or limit functionality of any computer software or hardware or telecommunications equipment;'),
                const Text(
                    '\nManipulating Service identifiers in order to disguise the origin of any content transmitted via the Services;'),
                const Text(
                    '\nCollecting or storing personal data about other users;'),
                const Text(
                    '\nInterfering with or disrupting the Service or servers or networks connected to the Service, or disobeying any requirements, procedures, policies or regulations of networks connected to the Service;'),
                const Text(
                    '\nUsing any robot, spider, website search/retrieval application, or other device to retrieve or index any portion of the Service or collect information about users for any unauthorized purpose; or'),
                const Text(
                    '\nCreating user accounts by automated means or under false or fraudulent pretenses.'),
                const Text(
                  '\nSEVERABILITY',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nIf any provision of this Agreement is determined to be invalid or unenforceable in whole or in part, such invalidity or unenforceability shall attach only to such provision or part of such provision and the remaining part of such provision and all other provisions of this Agreement shall continue to be in full force and effect.'),
                const Text(
                  '\nCHARGES AND FEES ASSOCIATED WITH PRE-PAID INSTRUMENTS',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nPlease note that there may be transaction fees at special merchant categories such as fuel stations etc. These charges will be applicable to the purchasers of the respective instruments and are subject to the agreement with them and may vary from case-to-case basis.'),
                const Text(
                  '\nCUSTOMER GRIEVANCE REDRESSAL POLICY',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nBachat Cards shall address any discrepancies and grievances of all the Users with respect to processing of information in a time bound manner. For detailed Customer Grievance Redressal Policy, please click here.'),
                const Text(
                  '\nGOVERNING LAW AND DISPUTE RESOLUTION',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nExcept as otherwise described, all content availed by the use of this Website/interface are made available only to facilitate the users. Bachat Card controls and operates the Website and Services and makes no representation that the contents and Services are appropriate or available for use in other locations. If you use the Services from a location other than the location where the Website and Services are controlled and operated, you are responsible for compliance with applicable local laws.'),
                const Text(
                    '\nThese Terms shall be governed by and shall be construed in accordance with the laws of India. All disputes relating to these Terms shall be settled in the courts located at Noida, India.'),
                const Text(
                  '\nHEADINGS',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nThe headings and subheadings herein are included for convenience and identification only and are not intended to describe, interpret, define or limit the scope, extent or intent of this Agreement, the terms of Service or the right to use the Portal by the Users contained herein or any other section or pages of the Portal in any manner whatsoever.'),
                const Text(
                  '\nNOTICES',
                  style: TextStyle(fontWeight: FontWeight.w500),
                ),
                const Text(
                    '\nAll notices and communications shall be in writing, in English and shall deemed given if delivered personally or by commercial messenger or courier service, or mailed by registered or certified mail (return receipt requested) or sent via email/ facsimile, with due acknowledgment of complete transmission to the following address:'),
                const Text(
                    '\nB-604 Aditya Mega City, Indirapuram, Ghaziabad, Uttar Pradesh-201014'),
                const SizedBox(
                  height: 8,
                )
              ]),
      )),
    );
  }

  Widget _textWithPaddingAndCenter(String text) {
    return TableCell(
      verticalAlignment: TableCellVerticalAlignment.middle,
      child: Padding(
        padding: const EdgeInsets.all(10),
        child: Text(text),
      ),
    );
  }

  Table _table() {
    return Table(
      columnWidths: const {
        0: FlexColumnWidth(1),
        1: FlexColumnWidth(2),
        2: FlexColumnWidth(4)
      },
      border: const TableBorder(
        horizontalInside: BorderSide(),
        top: BorderSide(),
        left: BorderSide(),
        right: BorderSide(),
        bottom: BorderSide(),
      ),
      children: [
        TableRow(children: [
          _textWithPaddingAndCenter('Sr'),
          _textWithPaddingAndCenter('MCC'),
          _textWithPaddingAndCenter('Merchant Category')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('1'),
          _textWithPaddingAndCenter('6010'),
          _textWithPaddingAndCenter(
              'Financial Institutions\' Manual Cash Disbursements')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('2'),
          _textWithPaddingAndCenter('6011'),
          _textWithPaddingAndCenter(
              'Financial Institutions\' Automated Cash Disbursements')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('3'),
          _textWithPaddingAndCenter('6012'),
          _textWithPaddingAndCenter(
              'Financial Institutions\' Merchandise and Services')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('4'),
          _textWithPaddingAndCenter('6051'),
          _textWithPaddingAndCenter(
              'Non-Financial Institutions\' Foreign Currency, Money Orders (not wire transfer), and Traveler Cheques')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('5'),
          _textWithPaddingAndCenter('6211'),
          _textWithPaddingAndCenter('Security Brokers and Dealers')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('6'),
          _textWithPaddingAndCenter('6300'),
          _textWithPaddingAndCenter(
              'Insurance Sales, Underwriting, and Premiums')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('7'),
          _textWithPaddingAndCenter('6513'),
          _textWithPaddingAndCenter('Real Estate Agents and Managers\' Rentals')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('8'),
          _textWithPaddingAndCenter('7012'),
          _textWithPaddingAndCenter('Timeshares')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('9'),
          _textWithPaddingAndCenter('4829'),
          _textWithPaddingAndCenter('Money Transfer')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('10'),
          _textWithPaddingAndCenter('5932'),
          _textWithPaddingAndCenter(
              'Antique Shops\' Sales, Repairs, and Restoration Services')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('11'),
          _textWithPaddingAndCenter('5933'),
          _textWithPaddingAndCenter('Pawn Shops')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('12'),
          _textWithPaddingAndCenter('5937'),
          _textWithPaddingAndCenter('Antique Reproductions')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('13'),
          _textWithPaddingAndCenter('5960'),
          _textWithPaddingAndCenter('Direct Marketing\' Insurance Services')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('14'),
          _textWithPaddingAndCenter('5970'),
          _textWithPaddingAndCenter('Artistic Supply and Craft Shops')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('15'),
          _textWithPaddingAndCenter('5971'),
          _textWithPaddingAndCenter('Art Dealers and Galleries')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('16'),
          _textWithPaddingAndCenter('5972'),
          _textWithPaddingAndCenter('Stamp and Coin Stores')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('17'),
          _textWithPaddingAndCenter('5973'),
          _textWithPaddingAndCenter('Religious Goods Stores')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('18'),
          _textWithPaddingAndCenter('5993'),
          _textWithPaddingAndCenter('Cigar Stores and Stands')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('19'),
          _textWithPaddingAndCenter('7277'),
          _textWithPaddingAndCenter(
              'Counseling Services\' Debt, Marriage, Personal')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('20'),
          _textWithPaddingAndCenter('7273'),
          _textWithPaddingAndCenter('Dating and Escort Services')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('21'),
          _textWithPaddingAndCenter('7297'),
          _textWithPaddingAndCenter('Massage Parlors')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('22'),
          _textWithPaddingAndCenter('7299'),
          _textWithPaddingAndCenter(
              'Miscellaneous Personal Services (Not Elsewhere Classified)')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('23'),
          _textWithPaddingAndCenter('7321'),
          _textWithPaddingAndCenter('Consumer Credit Reporting Agencies')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('24'),
          _textWithPaddingAndCenter('7361'),
          _textWithPaddingAndCenter(
              'Employment Agencies and Temporary Help Services')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('25'),
          _textWithPaddingAndCenter('7375'),
          _textWithPaddingAndCenter('Information Retrieval Services')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('26'),
          _textWithPaddingAndCenter('7393'),
          _textWithPaddingAndCenter(
              'Detective Agencies, Protective Agencies, and Security Services, including Armored Cars and Guard Dogs')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('27'),
          _textWithPaddingAndCenter('7399'),
          _textWithPaddingAndCenter(
              'Business Services (Not Elsewhere Classified)')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('28'),
          _textWithPaddingAndCenter('7995'),
          _textWithPaddingAndCenter(
              'Betting, including Lottery Tickets, Casino Gaming Chips, Off-Track Betting, and Wagers at Race Tracks')
        ]),
        TableRow(children: [
          _textWithPaddingAndCenter('29'),
          _textWithPaddingAndCenter('8651'),
          _textWithPaddingAndCenter('Political Organizations')
        ]),
      ],
    );
  }
}
